name: login_signup
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  fluttertoast: ^8.0.4
  flutter_session: ^0.1.1
  flutter_spinkit: ^5.1.0
  image_picker: ^0.8.0+4
  http: ^0.13.3
  get: ^4.3.8
  image_cropper: ^1.4.1
  pull_to_refresh: ^2.0.0
  flutter_local_notifications: ^4.0.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  androind: true
  ios: true
  image_path: "assets/icon/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/user.png
    - assets/images/login.png
